# Generated by Django 3.1.5 on 2021-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20210205_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
